feat : ElasticSearch 이용하여 사용자 검색 API 마이그레이션
8-Sprinters/ListyWave-back pull request #265
Opened 2024-05-26 06:23 UTC by pparkjs

# Description
**드디어 ElasticSearch, Logstash, Kibana 통칭 ELK를 이용하여 사용자 검색 API를 마이그레이션을 완료하였습니다!!**

### ✨**ELK 각각의 역할**
- ElasticSearch  
  1. User에 대한 데이터를 NoSQL로 데이터 역색인하여 저장함,   ( 역색인은 검색 성능에 아주 뛰어난 최적화 역할을함 )
  2. 엘라스틱서치에서는 형태소 분석을 통한 자연어 처리가 가능하며 Full-text 검색을 가능하게 함

- Logstash
  1. Mysql의 Users 테이블과 ElasticSearch에 User에 대한 index의 데이터 sync를 맞추기 위한 중간 파이프라인 역할을 함
  2. Mysql sync 뿐만 아니라 추후 로그를 Logstash를 이용하여 받아 가공하여 kibana에서 다양한 로그를 보기 편하게 관리할 수 있음
 
- Kibana
  1. ElasticSearch에 index들이나 console등을 잘 꾸며진 웹으로 한눈에 보면서 관리할 수 있는 역할을 함

### 👍**마이그레이션 하면서 얻은 효과**
#### **1. 매우 빨라진 검색성능**
**AS-IS** : 추후 사용자가 무수히 많아진다 가정 하였을때 기존 관계형 데이터베이스에서 사용자를 검색을 하면 index를 설정한다 하더라고 뛰어난 성능을 기대하기 어려움
 
**TO-BE** : ElasticSeach를 적용하므로써 역색인 지원으로 매우 빠른 검색이 가능하게 됨
`※ 기존 색인방식은 책 앞장에 목차라고 한다면, 역색인은 책 맨뒤에 단어별 페이지 확인 이라고 생각하면됨!`

#### **2. 다양한 검색 방식**
**AS-IS** : 기존 관계형 데이터베이스에서는 단순 텍스트매칭에 대한 검색만을 지원함 
ex ) LIKE ‘%단어%’ 검색시 완벽한 전문 검색(Full Text Search)은 지원하지 않는다.
 
**TO-BE** : 형태소 분석, 문자의 자소 처리, Full-text 검색 등을 analyzer를 통해 다양한 텍스트 분석을 한 뒤 score를 매겨 풍부한 검색이 가능하게 됨
ex) 
![image](https://github.com/8-Sprinters/ListyWave-back/assets/107859870/f5df8018-f2b2-4eed-95f0-8310d047f2be)
![image](https://github.com/8-Sprinters/ListyWave-back/assets/107859870/aecec76e-bd02-4960-adcc-2b640ce0da8c)
![image](https://github.com/8-Sprinters/ListyWave-back/assets/107859870/73869065-41f7-4d91-ab0e-15d52cb0cabc)
![image](https://github.com/8-Sprinters/ListyWave-back/assets/107859870/98d6d889-f93b-4500-96f7-aa74e352c082)

아래는 실제 사용되는 작성한 api이며 이를 [Elasticsearch Java API Client [8.13]를 이용하여 java로 해당 쿼리를 무한페이징이 가능하도록 풀어냄
```
GET users_sync_idx_v2/_search
{
  "query": {
    "bool": {
      "must_not": [
        {
          "term": {
            "_id": "-1"
          }
        }
      ],
      "should": [
        {
          "bool": {
            "must": [
              {
                "match": {
                  "nickname.ngram": {
                    "query": "정수",
                    "boost": 2
                  }
                }
              },
              {
                "term": {
                  "is_delete": false
                }
              }
            ]
          }
        },
        {
          "bool": {
            "must": [
              {
                "match": {
                  "nickname.jaso": {
                    "query": "정수",
                    "boost": 1.5
                  }
                }
              },
              {
                "term": {
                  "is_delete": false
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

### 👀**고려사항 및 직면한 문제**
- **고려사항**
  - 별도로 EC2 서버에 docker-es파일을 이미 업로드 하여 docker-compose로 ELK 구성 해 놓은 상태이며 commit한 docker-es 파일은 동호님에게 같이 공유 드리고 기록으로 남기기 위해 하였습니다!
  - Mysql의 Users와 ElasticSearch의 user index는 서로 sync가 맞도록 설계 되어 있어 Users 데이터가 수정 or 추가되면 ElasticSearch에 반영이 됩니다.  
 하지만 강력 삭제에 대해서는 고려할 수 없기에 추후 구현될 스케쥴링 이용하여 한달 지난 탈퇴 사용자 삭제를 구현할 때 ElasticSearch에도 삭제 요청을 같이 구현해야합니다! 
- **직면한 문제**
  - 현재 배포중인 ec2의 인스턴스 유형을 t4g.micro로 사용하고 있어 메모리가 1G 뿐 되지 않아 ELK가 동작 되면 메모리가 많이 부족하여 서버 성능이 현저히 느려지는 이슈가 있습니다. 이는 t4g.medium (메모리 4G)로 업그레이드 하면 해결 될 거 같지만 비용적인 문제가 발생되어 팀원과 상의 후 결정해야 할 거 같습니다 ㅠㅠ

# Reference
- https://esbook.kimjmin.net/05-search/5.1-query-dsl
- https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/connecting.html
- https://ksb-dev.tistory.com/320

# Relation Issues
- close #230

2024-05-27 02:27 UTC, kdkdhoho requested changes
어우.. 엘라스틱 서치를 적용하시다니.... 진심 대단하면서 부럽습니다 👍👍👍👍
조만간 ElasticSearch, LogStash, Kibana에 대해서 간단하게 설명 해주시면 감사하겠습니다 ㅎㅎ

여러 궁금증이나 코드에 대한 리뷰 남겨두었으니 확인 부탁드릴게요~~
너무너무 수고 많으셨습니다!

+ 질문)
1. MySQL의 데이터와 ES의 데이터 동기화를 위해 LogStash를 사용한다고 하셨는데, 어떤 식으로 동작되는 지 궁긍합니다.
2. Kibana는 현재 어떻게 활용되고 있나요? 추후 서버 모니터링 대시보드를 구축할 때 Kibana를 활용할 수 있나요?

2024-05-27 02:27 UTC, kdkdhoho commented on docker-es/logstash/mysql-connector-j-8.0.33.jar
이 jar 파일은 왜 필요한가요??

2024-05-27 02:27 UTC, kdkdhoho commented on docker-es/docker-compose.yml
> +      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
이 옵션은 메모리 사용량을 제한하는건가요??

2024-05-27 02:27 UTC, kdkdhoho commented on docker-es/docker-compose.yml
멋지다 이 남자 .. 👍

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/resources/elastic/user/es-setting.json
전체적으로 설명 한 번 부탁드려도 될까요 🥲

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/resources/elastic/user/es-mapping.json
요것도 설명 듣고 싶습니다..!

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/application/service/UserService.java
> +    public UserElasticSearchResponse searchUserByElastic(Long loginUserId, String search, Pageable pageable) {
`Long loginUserId` 앞에 `@Nullable` 추가해주세요!

```suggestion
    public UserElasticSearchResponse searchUserByElastic(@Nullable Long loginUserId, String search, Pageable pageable) {
```

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/application/service/UserService.java
> +    private UserElasticSearchResponse createUserSearchResponseByElastic(Long loginUserId, String search, Pageable pageable) {
ditto

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/presentation/UserController.java
> +    @GetMapping("/v2/users")
👍

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/presentation/UserController.java
> +            @RequestParam(name = "search", defaultValue = "") String search,
혹시 검색어를 의미하는 변수명이라면 search 대신, keyword는 어떠신가요?

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    public Map<String, Object> findAllByElasticSearch(String search, Pageable pageable, Long loginUserId) {
Service 계층과 파라미터 순서를 통일시키는 건 어떤가요??

```suggestion
    public Map<String, Object> findAllByElasticSearch(Long loginUserId, String search, Pageable pageable) {
```

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    private Query buildMatchQuery(String field, String search, float boost) {
`boost`는 어떤 의미를 가지는 값인가요?

그리고 타입이 `double`이 아닌 `float`이어야 하는 이유가 있나요??

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +        Query nicknameJasoQuery = buildMatchQuery("nickname.jaso", search, 1.5f);
`boost`에 해당하는 값을 상수로 나타내는 건 어떠신가요??

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +                );
아래처럼 정리하는 건 어떠신가요??

```suggestion
SearchRequest searchRequest = 
                buildSearchRequest(pageable, excludeUserIdQuery, isNotDeletedQuery, nicknameNgramQuery, nicknameJasoQuery);
```

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +        List<UserElasticSearchResult> results = processSearchResults(searchResponse);
그리고 여기 있는 공백들은 모두 제거해서 한 줄씩 작성하는게 더 깔끔해보입니다 !

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    private SearchResponse<UserDocument> executeSearchRequest(SearchRequest searchRequest) {
메서드 명을 간략하게 `requestSearch`나 `search`로 하는 건 어떠신가요??

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    public Map<String, Object> findAllByElasticSearch(String search, Pageable pageable, Long loginUserId) {
메서드 명에 `ByElasticSearch`는 없어도 될 것 같아요!

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +        );
아래와 같이 간결하게 작성할 수 있을 것 같아요.

```java
return SearchRequest.of(sr -> sr
        .index("users_sync_idx")
        .query(q -> q.bool(
                        b -> b.mustNot(excludeUserIdQuery)
                                .should(s -> s.bool(bb -> bb.must(nicknameNgramQuery, isNotDeletedQuery)))
                                .should(s -> s.bool(bb -> bb.must(nicknameJasoQuery, isNotDeletedQuery)))
                )
        )
        .from(offset)
        .size(pageable.getPageSize() + 1)
);
```

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    private List<UserElasticSearchResult> processSearchResults(SearchResponse<UserDocument> searchResponse) {
`process` 보다 `convert`가 더 확 와닿을 것 같습니다

2024-05-27 02:27 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    public Map<String, Object> findAllByElasticSearch(String search, Pageable pageable, Long loginUserId) {
반환 타입을 `Map<String, Object>` 가 아닌, 따로 DTO 객체를 반환하도록 하는 것이 좋을 듯 합니다!

아니면 차라리 Repository에서 바로 `UserElasticSearchResponse` 를 반환하도록 해도 좋을 듯 합니다. 만약 이렇게 하신다면, 패키지 참조 방향이 역순이 되지 않도록만 신경 써주세요!

2024-05-28 06:08 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +        }
catch하는 예외의 범위를 좁히는 게 좋을 것 같아요~!

2024-05-28 08:34 UTC, pparkjs commented
@kdkdhoho 

**1. MySQL의 데이터와 ES의 데이터 동기화를 위해 LogStash를 사용한다고 하셨는데, 어떤 식으로 동작되는 지 궁긍합니다.**

>   docker-es/logstash/pipeline/logstash.conf 를 확인해보시면 input, filter, output 블록이 보이실 겁니다.
>   (1). input 블록 코드를 보시면 사용하는 DB와 연결하는 작업과 Users 테이블의 update_date 컬럼을 기준으로 변경된 데이터를 가져 오도록 작성함
>   (2). filter 블록은 가져온 데이터를 ES에 index로 만들기 전에 중간 가공 및 필터링할 로직을 작성 하였으며 Users의 id 컬럼을 index(테이블이라 생각하면 됨)에서 사용하는 키의 값으로 사용하기 위한 복사 과정이며 필요없는 필드를 삭제함
>   (3).output 블록은 수집한 데이터를 elasticsearch로 전송하기 위한 블록임 필드의 역할들은 보면 이해될겁니다!
>   
>   최종적으로 mysql에 Users 테이블에 수정이 이뤄지거나 삽입이 이뤄지면 update_date 변경 감지로 elastic search index에 반영이 되는겁니다!

**2. Kibana는 현재 어떻게 활용되고 있나요? 추후 서버 모니터링 대시보드를 구축할 때 Kibana를 활용할 수 있나요?**

>   키바나는 현재 사용자 index를 한눈의 관리 하는 용도로 사용되고 있으며 index에 대한 setting이나 mapping , api, analyzer, tokenizer 등등 mysql console 처럼 명령어로 응답값을 받을 수 있는 환경을 제공합니다.
>   
>   모니터링 대시보드를 구축해보진 않아서 잘 모르겠지만.
>   
>   spring boot api 서버에서 생기는 각종 에러들을 logstash의 input으로 받아 원하는 포맷으로 가공하여 elasticsearch로 보내서 kibana로 각종 로그를 날짜별 index로 검색이 가능한 대쉬보드로 사용할 수 있습니다.

2024-05-28 08:35 UTC, pparkjs commented on docker-es/logstash/mysql-connector-j-8.0.33.jar
logstash.conf 파일을 확인해보시면 input 블록에 jdbc_driver_library필드 에서 mysql을 연결하기 위해 사용되고 있습니다!

2024-05-28 08:38 UTC, pparkjs commented on docker-es/docker-compose.yml
> +      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
Elasticsearch의 Java Virtual Machine (JVM) 설정을 정의하는 데 사용됩니다!
Java의 힙 메모리 크기를 설정하는 환경변수로
Xmx = 최대 힙 크기 , Xms = 최소 힙 크기를 설정한 것입니다!

2024-05-28 08:39 UTC, pparkjs commented on docker-es/docker-compose.yml
하핫 저도 다 구글링해서 긁어오면서 공부하여 맞춤으로 변형한 것입니다 ^^..

2024-05-28 08:41 UTC, pparkjs commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    private SearchResponse<UserDocument> executeSearchRequest(SearchRequest searchRequest) {
제안 감사드려요!

2024-05-28 08:41 UTC, pparkjs commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    public Map<String, Object> findAllByElasticSearch(String search, Pageable pageable, Long loginUserId) {
findAll만 해도 충분할 거 같단거죠!

2024-05-28 08:42 UTC, pparkjs commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +        );
뭔가 실제 api는 json 형식이라 json 레벨을 나눈 것을 시각화 하고자 저렇게 하긴 했었는데
굳이 그건 필요 없을 거 같고 확실히 동호님이 제안하신게 더 깔끔할 거 같네요!

2024-05-28 08:42 UTC, pparkjs commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    private List<UserElasticSearchResult> processSearchResults(SearchResponse<UserDocument> searchResponse) {
제안 감사합니다 ㅎ

2024-05-28 08:43 UTC, pparkjs commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    public Map<String, Object> findAllByElasticSearch(String search, Pageable pageable, Long loginUserId) {
이 부분 고민했었는데 그때 당시 갑자기 map먼저 떠올려서 그렇게 한거 같네요 DTO로 반환하도록 수정해볼게요!

2024-05-28 08:43 UTC, pparkjs commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +        }
알겠슴돠 ㅎㅎ

2024-05-28 13:40 UTC, kdkdhoho commented on docker-es/docker-compose.yml
> +      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
아 엘라스틱 서치가 JVM 기반으로 만들어졌나보군요 !?

2024-05-28 13:41 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    public Map<String, Object> findAllByElasticSearch(String search, Pageable pageable, Long loginUserId) {
넵 !

2024-05-29 02:11 UTC, pparkjs commented on src/main/resources/elastic/user/es-setting.json
설명에 앞서 es-setting.json과 es-mapping.json 파일은 elasticSearch에 해당 user_sync_index가 존재 하지 않을 때 spring data elasticsearch 를 이용하여 UserDocument를 insert 하는 api 호출을 보냈을 때 index가 생성되면서 setting과 mapping이 적용이 됩니다.

하지만 logstash를 통해 mysql과 sync를 맞췄을 때 기존 mysql의 Users테이블에 모든 데이터를 logstash를 통해 삽입하는 과정에서 elasticsearch가 자체적으로 index가 생성되면서 필드에 맞게 default mapping과 setting이 설정 되었습니다 .
**_※ 이미 index에 한 번 설정된 mapping과 setting은 수정하기 어렵거나 안됨_**

그래서 제가 원하는 mapping과 setting을 설정하기 위해 kibana console을 이용하여 새로운 index를 만들면서 custom mapping과 setting을 입혀줬습니다. ( 이때 custom mapping, setting은 해당 json파일들이며 해당 코드를 직접 가져다 사용함 )

결론적으로는 commit한 setting과 mapping 파일은 사실 현재로써 의미는 없지만 내용을 공유하기 위해 commit 했다고 보면 됨

👉 작업 순서 : 
1. logstash 이용하여 index생성(users_sync_index_v2) -> default setting, mapping이 설정되어 있음
2. kibana console에서 임의로 index생성(users_sync_index) -> 생성할 때 custom setting, mapping 설정
3. users_sync_index_v2에 있던 데이터 users_sync_index로 옮김
3. logstash.conf에 users_sync_index_v2로 되있는거 -> users_sync_index로 변경 후 재실행

### 💡 setting 간략 설명

Analyzer (분석기)
- 분석기는 텍스트를 색인(index)할 때 사용되는 프로세스로, 텍스트를 일련의 토큰(token)으로 분해하고, 각 토큰에 대해 추가적인 처리를 수행합니다. 분석기는 토크나이저와 필터의 조합으로 구성됩니다!

Tokenizer (토크나이저)

2024-05-29 02:23 UTC, pparkjs commented on src/main/resources/elastic/user/es-setting.json
설명에 앞서 es-setting.json과 es-mapping.json 파일은 elasticSearch에 해당 user_sync_index가 존재 하지 않을 때 spring data elasticsearch 를 이용하여 UserDocument를 insert 하는 api 호출을 보냈을 때 index가 생성되면서 setting과 mapping이 적용이 됩니다.

하지만 logstash를 통해 mysql과 sync를 맞췄을 때 기존 mysql의 Users테이블에 모든 데이터를 logstash를 통해 삽입하는 과정에서 elasticsearch가 자체적으로 index가 생성되면서 필드에 맞게 default mapping과 setting이 설정 되었습니다 .
**_※ 이미 index에 한 번 설정된 mapping과 setting은 수정하기 어렵거나 안됨_**

그래서 제가 원하는 mapping과 setting을 설정하기 위해 kibana console을 이용하여 새로운 index를 만들면서 custom mapping과 setting을 입혀줬습니다. ( 이때 custom mapping, setting은 해당 json파일들이며 해당 코드를 직접 가져다 사용함 )

결론적으로는 commit한 setting과 mapping 파일은 사실 현재로써 의미는 없지만 내용을 공유하기 위해 commit 했다고 보면 됨

👉 작업 순서 : 
1. logstash 이용하여 index생성(users_sync_index_v2) -> default setting, mapping이 설정되어 있음
2. kibana console에서 임의로 index생성(users_sync_index) -> 생성할 때 custom setting, mapping 설정
3. users_sync_index_v2에 있던 데이터 users_sync_index로 옮김
3. logstash.conf에 users_sync_index_v2로 되있는거 -> users_sync_index로 변경 후 재실행

### 💡 setting 간략 설명

**Analyzer (분석기)**
- 분석기는 텍스트를 색인(index)할 때 사용되는 프로세스로, 텍스트를 일련의 토큰(token)으로 분해하고, 각 토큰에 대해 추가적인 처리를 수행합니다. 분석기는 토크나이저와 필터의 조합으로 구성됩니다!

**Tokenizer (토크나이저)** 
- 토크나이저는 텍스트를 개별 단어 또는 토큰으로 나누는 역할을 합니다. 
ex ) "박정수는 백엔드 개발자 입니다"라는 문장을 "박정수", "는", "백엔드", "개발자", "입니다"로 나눕니다.

**Filter (필터)**
- 필터는 토크나이저로 분해된 토큰에 추가적인 처리를 수행합니다. 
ex ) 토큰을 소문자로 변환하거나, 불용어(stop words)를 제거하는 등의 작업을 수행합니다!

**n-gram과 자소(jaso)**
- n-gram: n-gram은 텍스트를 n개의 연속된 문자 단위로 분해하는 방법입니다. 
ex ) "Elasticsearch"를 3-gram으로 분해하면 "Ela", "las", "ast", "sta", "tar", "arc", "rch"와 같은 식으로 나눌 수 있습니다. n-gram은 부분 검색이나 오타 교정에 유용합니다! 

- 자소 : 자소는 한국어 문자를 자음과 모음 단위로 분해하는 방법입니다. 
ex )  "가"는 "ㄱ"과 "ㅏ"로 "a"는 "ㅁ"로 분해 및 분됩니다. 자소 분해는 한국어 검색에서 특히 유용하며, 자음과 모음의 오타를 교정하거나 비슷한 발음의 단어를 검색하는 데 도움이 됩니다.

**전체적인 설명**
- 해당 설정 파일은 다양한 텍스트 분석 및 검색 기능을 지원하기 위해 설계되었습니다. n-gram 필터와 토크나이저를 사용하여 부분 검색과 오타 교정을 지원하고, 자소 단위 토크나이저를 통해 한국어 텍스트의 검색 품질을 향상시키도록 설정해 놓았습니다!

2024-05-29 02:27 UTC, pparkjs commented on src/main/resources/elastic/user/es-mapping.json
해당 mapping은 users_sync_index 에 필드에 타입을 매핑하는 역할을 합니다!

특이사항으로는 아래 nickname부분 일텐데 이는 setting에 설정한 analyzer를 해당 nickname을 검색할 때 사용하기 위하여 지정해 준 거라 생각하시면 됩니다!
ngram과 jaso 두가지의 type으로 해서 더 풍부한 검색결과가 나올 수 있도록 했습니다!

```
    "nickname": {
      "type": "text",
      "fields": {
        "ngram": {
          "type": "text",
          "analyzer": "my_ngram_analyzer"
        },
        "jaso": {
          "type": "text",
          "analyzer": "suggest_index_analyzer",
          "search_analyzer": "suggest_search_analyzer"
        }
      }
    },
```

### jaso 에서 인덱싱과 검색을 분리한 이유
- 인덱싱: suggest_index_analyzer를 사용하여 텍스트를 인덱싱할 때는 모든 가능한 조합(자음, 모음, 초성 포함)을 인덱스에 저장합니다. 이렇게 하면 검색 시 다양한 입력 방식에 대해 유연하게 대응할 수 있습니다.
- 검색: suggest_search_analyzer는 검색어를 분석할 때 초성을 제외하고 분석합니다. 이는 검색어가 불완전하거나 부분적인 경우에도 정확한 결과를 반환하도록 도와줍니다.

2024-05-29 04:23 UTC, pparkjs commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    private Query buildMatchQuery(String field, String search, float boost) {
boost는 score에서 boost 만큼 배수의 가중치를 더 주겠다는 것 입니다!

타입은 아래 타입이 Float로 지정되어 있기 때문입니다!
![image](https://github.com/8-Sprinters/ListyWave-back/assets/107859870/970d43eb-9171-4d3b-9d8a-ca82b6aef6be)

2024-05-29 06:17 UTC, kdkdhoho reviewed
반영하신 것 확인했습니다!
코멘트 한 번만 더 확인 부탁드릴게요!!

바쁘실텐데 마지막까지 파이팅 💪

2024-05-29 06:17 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    private final ElasticsearchClient esClient;
상수와 변수 사이에 공백 한 줄 추가하는 것이 컨벤션입니다!

```suggestion
    private static final float NGRAM_BOOST = 2.0f;
    private static final float JASO_BOOST = 1.5f;
    
    private final ElasticsearchClient esClient;
```

2024-05-29 06:17 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +import com.listywave.user.application.dto.search.UserElasticSearchResult;
Repository 계층이 Application 계층을 참조하고 있습니다 😨

2024-05-29 06:17 UTC, kdkdhoho commented on src/main/java/com/listywave/user/application/service/UserService.java
> +            return userElasticRepository.findAll(-1L, keyword, pageable);
loginUserId가 null일 때 -1L을 넘기는 이유가 궁금합니다!

2024-05-29 06:57 UTC, pparkjs commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +import com.listywave.user.application.dto.search.UserElasticSearchResult;
제가 생각했을 때는 기존에 repository에서 queryDsl로 구현할때 아래와 같이 Projections을 이용하여 DTO로 반환 받도록 
설게가 되어 있으며 이 방식은 성능 최적화로 많이 사용하고 있고 권장되는 방식이기도 합니다! 
꼭 DTO를 반환안한다하더라고 반환타입이 Users Entity 인경우도 필수적으로 생겨나면서 Application 계층을 참조하게 되고요!!

제가 작성한 Repository도 이와 마찬가지라고 생각이 됩니다!
이게 ElasticSearch가 아니더라도 기존에 모든 repository는 Entity or dto 반환 위한 Projection 방식을 통해 모두 Application 계층을 참조하고 있는데 혹시 이 부분은 뭔가 다른 점이 있는 건지 감이 잘 오지 않습니다!

```
        List<UserSearchResult> fetch = queryFactory
                .select(Projections.fields(UserSearchResult.class,
                        user.id,
                        user.nickname.value.as("nickname"),
                        user.profileImageUrl.value.as("profileImageUrl")
                ))
                .from(user)
                .where(
```

2024-05-29 06:57 UTC, pparkjs commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +    private final ElasticsearchClient esClient;
앗 몰랐습니다 ㅎㅎ 감사합니다!

2024-05-29 07:00 UTC, pparkjs commented on src/main/java/com/listywave/user/application/service/UserService.java
> +            return userElasticRepository.findAll(-1L, keyword, pageable);
findAll 메서드를 확인해보시면 로그인한 유저는 자신을 제외한 검색결과가 나와야 하는데
비회원은 모든 사용자를 나타내야 하기에 id = -1 로 조건으로 한것입니다! 
null로 안넣은 이유는 타입을 일치해서 파라미터를 받아야 컴파일 시점 에러가 안나기 때문입니다!

2024-05-31 07:23 UTC, kdkdhoho commented on src/main/java/com/listywave/user/repository/user/elastic/UserElasticRepository.java
> +import com.listywave.user.application.dto.search.UserElasticSearchResult;
음, 생각해보니 그렇군요 제가 너무 일차원적으로만 생각했던 것 같아요..!
일단 이건 이렇게 두는 걸로 하죠 ㅎㅎ

2024-06-02 10:38 UTC, kdkdhoho approved these changes
최고최고 👍👍👍👍
너무너무 수고하셨습니다 !! 이제 얼른 인스턴스 관련 문제만 해결하면 되겠군요.
사용자 검색 API 성능 기대하겠습니다 ㅎㅎ

2024-06-02 10:38 UTC, merged